In [26]:
class animal():
    '''this is doc'''
    def __init__(self,name,kind):   #构造函数
        self.name=name
        self.kind=kind
    def getName(self):
        return self.name
    def getKind(self):
        return self.kind
    def changeName(self,newname):
        self.name=newname
    def __str__(self):
        return (self.name+'---'+self.kind)

In [27]:
A=animal("cat","cat_kind")

In [28]:
print(A.__doc__)

this is doc


In [29]:
A=animal("cat","cat_kind")
print(A)

cat---cat_kind


In [30]:
class cat(animal):
    def __init__():
        pass

In [31]:
class Cat_asia(cat):
    def __init__:
        pass

SyntaxError: invalid syntax (<ipython-input-31-65f932dab048>, line 2)

In [33]:
from numpy import array
a=array([[0, 1, 2, 3, 4, 5],
        [10,11,12,13,14,15],
        [20,21,22,23,24,25],
        [30,31,32,33,34,35],
        [40,41,42,43,44,45],
        [50,51,52,53,54,55]])

In [34]:
import numpy as np

In [35]:
a[2,3]

23

In [37]:
a[0]#取第0行

array([0, 1, 2, 3, 4, 5])

In [39]:
a[:,0]#取第0列(所有行的第0列)

array([ 0, 10, 20, 30, 40, 50])

In [40]:
a[0,:]

array([0, 1, 2, 3, 4, 5])

In [41]:
a[3,:] #第3行所有列

array([30, 31, 32, 33, 34, 35])

In [43]:
a[3,2:4]

array([32, 33])

In [44]:
a[::2,::2]#行：0，2，4 列：0，2，4

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [45]:
a[(0,2,3),::2]#行：0，2，3 列：0，2，4

array([[ 0,  2,  4],
       [20, 22, 24],
       [30, 32, 34]])

In [46]:
a.max()

55

In [47]:
a.min()

0

In [48]:
a.sum()

990

In [50]:
a.mean()

27.5

In [51]:
a.std()#标准差

17.163430115607234

In [52]:
a.var()#方差

294.58333333333331

In [53]:
a.any()

True

In [54]:
a=np.zeros((15,15),dtype=int) #快速生成0数组

In [55]:
a

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [56]:
a.any()

False

In [57]:
a[0,0]=1
a

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [58]:
a.any()

True

In [59]:
a[:,0].any()

True

In [61]:
a=range(1,10)

In [62]:
a

range(1, 10)

In [63]:
np.arange(1,10) #快速生成数组

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
b=np.linspace(0,100,5)

In [65]:
b

array([   0.,   25.,   50.,   75.,  100.])